name: Deployment Automation
description: 
projects:
  - blazing
  - capistrano
  - dandelion
  - debloy
  - deprec
  - git-deploy
  - gofer
  - hercules
  - heroku
  - heroku-rails
  - heroku_san
  - inploy
  - instance_selector
  - mina
  - mpalmer/giddyup
  - negroku
  - paratrooper
  - pulsar
  - railsmachine/moonshine
  - remi/phd
  - rubber
  - ruploy
  - saizai/superdeploy
  - shelly
  - vigil
  - vlad
  - whiskey_disk
