name: Configuration Management
description: Configure your applications easily and securely
projects:
  - acts_as_configurable
  - amberbit-config
  - anyway_config
  - app
  - app_config
  - application_configuration
  - bridgetown_credentials
  - chamber
  - config
  - config-me
  - config_fun
  - config_newton
  - configatron
  - configliere
  - configloader
  - configtoolkit
  - configulations
  - configurability
  - configurable_engine
  - configuration
  - configus
  - confstruct
  - constantinople
  - dotconfig
  - dotenv
  - dotenv-rails
  - dry-configurable
  - dry-credentials
  - dynamic_configuration
  - envied
  - envyable
  - figaro
  - gaston
  - global
  - informante
  - ledermann-rails-settings
  - micon
  - nero
  - optimism
  - rails-settings
  - rails_config
  - rconfig
  - settingslogic
  - simpleconfig
  - store_configurable
  - tty-config
  - user_config
  - yaml_extend
  - yettings
